{% set name = "tiktoken" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d02a5ca6a938e0490e1ff957bc48c8b078c88cb83977be1625b1fd8aac792c5d

build:
  number: 0
  skip: True  # [py<39]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - wheel
    - setuptools >=62.4
    - setuptools-rust >=1.5.2
    - pip
  run:
    - python
    - libgcc-ng  # [linux]
    - regex >=2022.1.18
    - requests >=2.26.0
  run_constrained:
    - blobfile >=2

test:
  imports:
    - tiktoken
    - tiktoken_ext
  source_files:
    - tests/
  requires:
    - pip
    - pytest
    - hypothesis
  commands:
    - pip check
    - python -c "import tiktoken; enc = tiktoken.get_encoding('gpt2'); assert enc.encode('hello world') == [31373, 995]"
    - pytest tests --import-mode=append -vv

about:
  home: https://github.com/openai/tiktoken
  dev_url: https://github.com/openai/tiktoken
  doc_url: https://github.com/openai/tiktoken/blob/main/README.md
  summary: tiktoken is a fast BPE tokeniser for use with OpenAI's models
  description: tiktoken is a fast BPE tokeniser for use with OpenAI's models.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - BastianZim
